services:
  workspace:
    image: golang:1.20.4-alpine3.17
    restart: unless-stopped
    working_dir: /code/
    volumes:
      - ./:/code/
    command: sleep infinity

  requests-catcher:
    image: smarterdm/http-request-catcher
    restart: unless-stopped
    ports:
      - 5000:5000

  sentry-mattermost-sidecar:
    image: itsalex/alpine-reflex:latest
    restart: unless-stopped
    environment:
      - SMS_MATTERMOST_WEBHOOK_URL=http://requests-catcher:5000
    volumes:
      - ./:/code/
    ports:
      - 1323:1323
    command: reflex -g code/bin/sms -s /code/bin/sms